[package]
name = "distsys"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mrsequential"
path = "bin/mrsequential.rs"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }
regex = "1.11.1"
tokio = { version = "1.44.1", features = ["full"] }
